disable_functions = passthru,system,chroot,chgrp,chown,popen,dl,syslog,getservbyname,getservbyport,res_send,dns_get_record

memory_limit = 256M
date.timezone = Asia/Shanghai
; 正式环境中请改为 false
display_errors = false
