<?php

namespace App\Http\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * SS节点信息
 * Class SsNode
 *
 * @package App\Http\Models
 * @mixin \Eloquent
 */
class SsNode extends Model
{
    protected $table = 'ss_node';
    protected $primaryKey = 'id';

    protected $fillable = [
        'name', 'v2_name', 'node_rxtx', 'node_cpu', 'node_memory', 'node_disk',
        'bandwidth', 'node_unlock', 'info', 'level', 'node_group', 'node_cost',
        'traffic_limit', 'reset_day', 'sort', 'traffic_rate', 'country_code',
        'node_country', 'node_city', 'ip', 'ipv6', 'server', 'status',
        'is_clone', 'node_ids', 'type', 'node_health', 'last_raw_total', 'traffic_used',
        'server_uptime', 'heartbeat_at',
    ];

    protected $casts = [
        'node_cost' => 'float',
        'traffic_rate' => 'float',
        'is_clone' => 'integer',
        'node_health' => 'integer',
        'status' => 'integer',
        'node_cpu' => 'integer',
        'node_memory' => 'float',
        'node_disk' => 'float',
    ];

    /**
     * Get all clone nodes belonging to this main node.
     */
    function clones()
    {
        return $this->hasMany(SsNode::class, 'is_clone', 'id');
    }

    /**
     * Get the parent main node if this is a clone.
     */
    function parent()
    {
        return $this->belongsTo(SsNode::class, 'is_clone', 'id');
    }

    function label()
    {
        return $this->hasMany(SsNodeLabel::class, 'node_id', 'id');
    }

    function dnsRecords()
    {
        return $this->hasMany(DnsRecord::class, 'node_id', 'id');
    }

    function isotoemoji($iso)
    {
        $iso = strtolower($iso);
        $iso_to_emoji = array(
            'ac' => '🇦🇨',
            'ad' => '🇦🇩',
            'ae' => '🇦🇪',
            'af' => '🇦🇫',
            'ag' => '🇦🇬',
            'ai' => '🇦🇮',
            'al' => '🇦🇱',
            'am' => '🇦🇲',
            'ao' => '🇦🇴',
            'aq' => '🇦🇶',
            'ar' => '🇦🇷',
            'as' => '🇦🇸',
            'at' => '🇦🇹',
            'au' => '🇦🇺',
            'aw' => '🇦🇼',
            'ax' => '🇦🇽',
            'az' => '🇦🇿',
            'ba' => '🇧🇦',
            'bb' => '🇧🇧',
            'bd' => '🇧🇩',
            'be' => '🇧🇪',
            'bf' => '🇧🇫',
            'bg' => '🇧🇬',
            'bh' => '🇧🇭',
            'bi' => '🇧🇮',
            'bj' => '🇧🇯',
            'bl' => '🇧🇱',
            'bm' => '🇧🇲',
            'bn' => '🇧🇳',
            'bo' => '🇧🇴',
            'bq' => '🇧🇶',
            'br' => '🇧🇷',
            'bs' => '🇧🇸',
            'bt' => '🇧🇹',
            'bv' => '🇧🇻',
            'bw' => '🇧🇼',
            'by' => '🇧🇾',
            'bz' => '🇧🇿',
            'ca' => '🇨🇦',
            'cc' => '🇨🇨',
            'cd' => '🇨🇩',
            'cf' => '🇨🇫',
            'cg' => '🇨🇬',
            'ch' => '🇨🇭',
            'ci' => '🇨🇮',
            'ck' => '🇨🇰',
            'cl' => '🇨🇱',
            'cm' => '🇨🇲',
            'cn' => '🇨🇳',
            'co' => '🇨🇴',
            'cp' => '🇨🇵',
            'cr' => '🇨🇷',
            'cu' => '🇨🇺',
            'cv' => '🇨🇻',
            'cw' => '🇨🇼',
            'cx' => '🇨🇽',
            'cy' => '🇨🇾',
            'cz' => '🇨🇿',
            'de' => '🇩🇪',
            'dg' => '🇩🇬',
            'dj' => '🇩🇯',
            'dk' => '🇩🇰',
            'dm' => '🇩🇲',
            'do' => '🇩🇴',
            'dz' => '🇩🇿',
            'ea' => '🇪🇦',
            'ec' => '🇪🇨',
            'ee' => '🇪🇪',
            'eg' => '🇪🇬',
            'eh' => '🇪🇭',
            'er' => '🇪🇷',
            'es' => '🇪🇸',
            'et' => '🇪🇹',
            'eu' => '🇪🇺',
            'fi' => '🇫🇮',
            'fj' => '🇫🇯',
            'fk' => '🇫🇰',
            'fm' => '🇫🇲',
            'fo' => '🇫🇴',
            'fr' => '🇫🇷',
            'ga' => '🇬🇦',
            'gb' => '🇬🇧',
            'gd' => '🇬🇩',
            'ge' => '🇬🇪',
            'gf' => '🇬🇫',
            'gg' => '🇬🇬',
            'gh' => '🇬🇭',
            'gi' => '🇬🇮',
            'gl' => '🇬🇱',
            'gm' => '🇬🇲',
            'gn' => '🇬🇳',
            'gp' => '🇬🇵',
            'gq' => '🇬🇶',
            'gr' => '🇬🇷',
            'gs' => '🇬🇸',
            'gt' => '🇬🇹',
            'gu' => '🇬🇺',
            'gw' => '🇬🇼',
            'gy' => '🇬🇾',
            'hk' => '🇭🇰',
            'hm' => '🇭🇲',
            'hn' => '🇭🇳',
            'hr' => '🇭🇷',
            'ht' => '🇭🇹',
            'hu' => '🇭🇺',
            'ic' => '🇮🇨',
            'id' => '🇮🇩',
            'ie' => '🇮🇪',
            'il' => '🇮🇱',
            'im' => '🇮🇲',
            'in' => '🇮🇳',
            'io' => '🇮🇴',
            'iq' => '🇮🇶',
            'ir' => '🇮🇷',
            'is' => '🇮🇸',
            'it' => '🇮🇹',
            'je' => '🇯🇪',
            'jm' => '🇯🇲',
            'jo' => '🇯🇴',
            'jp' => '🇯🇵',
            'ke' => '🇰🇪',
            'kg' => '🇰🇬',
            'kh' => '🇰🇭',
            'ki' => '🇰🇮',
            'km' => '🇰🇲',
            'kn' => '🇰🇳',
            'kp' => '🇰🇵',
            'kr' => '🇰🇷',
            'kw' => '🇰🇼',
            'ky' => '🇰🇾',
            'kz' => '🇰🇿',
            'la' => '🇱🇦',
            'lb' => '🇱🇧',
            'lc' => '🇱🇨',
            'li' => '🇱🇮',
            'lk' => '🇱🇰',
            'lr' => '🇱🇷',
            'ls' => '🇱🇸',
            'lt' => '🇱🇹',
            'lu' => '🇱🇺',
            'lv' => '🇱🇻',
            'ly' => '🇱🇾',
            'ma' => '🇲🇦',
            'mc' => '🇲🇨',
            'md' => '🇲🇩',
            'me' => '🇲🇪',
            'mf' => '🇲🇫',
            'mg' => '🇲🇬',
            'mh' => '🇲🇭',
            'mk' => '🇲🇰',
            'ml' => '🇲🇱',
            'mm' => '🇲🇲',
            'mn' => '🇲🇳',
            'mo' => '🇲🇴',
            'mp' => '🇲🇵',
            'mq' => '🇲🇶',
            'mr' => '🇲🇷',
            'ms' => '🇲🇸',
            'mt' => '🇲🇹',
            'mu' => '🇲🇺',
            'mv' => '🇲🇻',
            'mw' => '🇲🇼',
            'mx' => '🇲🇽',
            'my' => '🇲🇾',
            'mz' => '🇲🇿',
            'na' => '🇳🇦',
            'nc' => '🇳🇨',
            'ne' => '🇳🇪',
            'nf' => '🇳🇫',
            'ng' => '🇳🇬',
            'ni' => '🇳🇮',
            'nl' => '🇳🇱',
            'no' => '🇳🇴',
            'np' => '🇳🇵',
            'nr' => '🇳🇷',
            'nu' => '🇳🇺',
            'nz' => '🇳🇿',
            'om' => '🇴🇲',
            'pa' => '🇵🇦',
            'pe' => '🇵🇪',
            'pf' => '🇵🇫',
            'pg' => '🇵🇬',
            'ph' => '🇵🇭',
            'pk' => '🇵🇰',
            'pl' => '🇵🇱',
            'pm' => '🇵🇲',
            'pn' => '🇵🇳',
            'pr' => '🇵🇷',
            'ps' => '🇵🇸',
            'pt' => '🇵🇹',
            'pw' => '🇵🇼',
            'py' => '🇵🇾',
            'qa' => '🇶🇦',
            're' => '🇷🇪',
            'ro' => '🇷🇴',
            'rs' => '🇷🇸',
            'ru' => '🇷🇺',
            'rw' => '🇷🇼',
            'sa' => '🇸🇦',
            'sb' => '🇸🇧',
            'sc' => '🇸🇨',
            'sd' => '🇸🇩',
            'se' => '🇸🇪',
            'sg' => '🇸🇬',
            'sh' => '🇸🇭',
            'si' => '🇸🇮',
            'sj' => '🇸🇯',
            'sk' => '🇸🇰',
            'sl' => '🇸🇱',
            'sm' => '🇸🇲',
            'sn' => '🇸🇳',
            'so' => '🇸🇴',
            'sr' => '🇸🇷',
            'ss' => '🇸🇸',
            'st' => '🇸🇹',
            'sv' => '🇸🇻',
            'sx' => '🇸🇽',
            'sy' => '🇸🇾',
            'sz' => '🇸🇿',
            'ta' => '🇹🇦',
            'tc' => '🇹🇨',
            'td' => '🇹🇩',
            'tf' => '🇹🇫',
            'tg' => '🇹🇬',
            'th' => '🇹🇭',
            'tj' => '🇹🇯',
            'tk' => '🇹🇰',
            'tl' => '🇹🇱',
            'tm' => '🇹🇲',
            'tn' => '🇹🇳',
            'to' => '🇹🇴',
            'tr' => '🇹🇷',
            'tt' => '🇹🇹',
            'tv' => '🇹🇻',
            'tw' => '🇹🇼',
            'tz' => '🇹🇿',
            'ua' => '🇺🇦',
            'ug' => '🇺🇬',
            'um' => '🇺🇲',
            'un' => '🇺🇳',
            'us' => '🇺🇸',
            'uy' => '🇺🇾',
            'uz' => '🇺🇿',
            'va' => '🇻🇦',
            'vc' => '🇻🇨',
            've' => '🇻🇪',
            'vg' => '🇻🇬',
            'vi' => '🇻🇮',
            'vn' => '🇻🇳',
            'vu' => '🇻🇺',
            'wf' => '🇼🇫',
            'ws' => '🇼🇸',
            'xk' => '🇽🇰',
            'ye' => '🇾🇪',
            'yt' => '🇾🇹',
            'za' => '🇿🇦',
            'zm' => '🇿🇲',
            'zw' => '🇿🇼',
        );

        if (empty( $iso_to_emoji[$iso] ) ){
            return '🇺🇳';
        }else{
            return $iso_to_emoji[$iso];
        }
    }
}